language: d
dist: xenial

d:
    - dmd
    - ldc

script:
    - wget https://www.openssl.org/source/openssl-1.1.1a.tar.gz
    - tar xzvf openssl-1.1.1a.tar.gz >/dev/null
    - cd openssl-1.1.1a
    - ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' >/dev/null
    - make >/dev/null
    - sudo make install >/dev/null
    - openssl version -a
    - cd ../
    - ls -la /usr/local/lib/
    - LD_LIBRARY_PATH=/usr/local/lib dub test --config=library --compiler=$DC
