language: d
dist: xenial

d:
    - dmd
    - ldc

script:
    - wget https://www.openssl.org/source/openssl-1.1.1a.tar.gz
    - tar xzvf openssl-1.1.1a.tar.gz
    - cd openssl-1.1.1a
    - ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
    - make
    - sudo make install
    - openssl version -a
    - cd ../
    - dub test --config=library --compiler=$DC
